apiVersion: v1
kind: Service
metadata:
  name: node-balancer
spec:
  type: LoadBalancer
  selector:
      app: node-print
  ports:
    - port: 80
      targetPort: 3001
      name: http
    - port: 443
      targetPort: 3001
      name: https