# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

https://computer.miniland1333.com/ay/secureAccess?key=38C5CB78D4AE5D69281712F5B682B4549FB8554964DDE6BF5EB34A0824AD9DF0

###
